### ISSUE TITLE
Kérés

### ISSUE THREAD

**Issue by ujvarivera** [Teaching-projects/SOE-ProgAlap1-Beadando-Blackjack-Ujvari#1]
Szia. Nem tudom még mit tudnék kihozni a beadandómból, amit kigondoltam az meg van. Nem tudom elegendő-e a kód, megfelel-e. Ha majd ránéznél valamikor, azt nagyon szépen köszönöm! :)

**Comment by hegyhati** [comment]
Elso blikkre jonak tunik, a kodot majd holnap(utan?) bogaraszom at bovebben.

**Comment by hegyhati** [comment]
`option.py`
 - [x] Itt nem latom, mi ertelme van ezt a kettot ket fuggvenybe szetszedni, meg rossznak is mondanam, mert elsetal egymastol a kerdes meg a lehetseges valaszok. Hagynam egy fuggvenyben.
 - [x] lletve akkor meg betennek ide egy ellenorzest, hogy addig kerje, amig ertelmes valaszt nem ad. Ennek a lekezelese most mashol van.

`main.py`
 - [x] Az options nem latom, minek van berantva, amikor nincs meghivva.
 - [x] Ez majd inkabb a cards-hoz fog tartozni, de nem szep az, hogy meghivod a cards-nak egy fuggvenyet fixen a cardsban definialt ket kartyalistaval. Ennek ugy lenne ertelme, ha itt lenne valami logika, aminel vagy betoltesz egy mentest, vagy 0-rol indulsz, es ennek megfeleloen kulonbozo modon parameterezed. Ha csak igy hivod meg, akkor felesleges ezekbol argumentumokat csinalni, a fuggveny torzseben is tudod inicializalni erre a listakat.

`cards.py`
 - [x] `sumOfTheCards` fuggvenynel ha lennenek tesztek, rajonnel, hogy nem mindig jol szamol. probald pl ki a `[3,10,'A']` listara, hogy mit csinal.
 - [x] az `if....` fuggvenyeidben nem olyan szep a pattern amit haznalsz. Egyreszt a `return False`-ok nem az `else` agban vannak, hanem "kint". Mivel most mindig egy `return True` van az `if` agban, ezert ez nem gond, de attol meg "csunyacska". De alapvetoen felesleges is ilyen bonyolultra megcsinalni, pl az `ifCardIsA` lehetne csak egy `return card=="A"`, es hasonloan a tobbi is. Meg egy nagyon minor megjegyzes ezekhez a fuggvenyekhez, hogy nem `if...` hanem inkabb `is...`-nak szoktak nevezni. 
 - [ ] A `get***Card` most ha jol ertem, nem veszi ki a paklibol azt, amit a jatekosnak, dealernek letettunk. Ez szandekos?
 - [x] A save funkcio nem olyan, amit be is toltenenk, szoval ennek lehet mas nevet adnek, mert igy kicsit felrevezeto. Illetve ennek lehet nem is csinalnek funkciot, hanem mondjuk minden jatek vegen automatikusan hozzafuzne egy log fajlhoz, amiben akkor benne lenne az osszes eddigi jatek eredmenye.
 - [x] no, a `main`-bol en igy akkor tenyleg inkabb kiszednem az argumentumokat, es a ket "kez" inicializalasat beirnam a fuggveny elejere, hogy legyen ures lista (es akkor ennek a tetejerol is ki lehet szedni.)
 - [x] A jatekszabalyokat most nem teljesen latom at (ha en megallok, meg kell-e allnia a dealernek, meg ilyenek), de felteve, hogy ez a logika jol mukodik, en kicsit atstrukturalnam a dolgot. A save ugye kikerulne. Az elso option teszteles ele odamehetne az exit-es, es akkor az `if optin==1 or ...` nem kell, mert ha idaig eljutottunk, akkor ez van. 
 - [x] Ez a fenti segitene kicsit jobban atlatni logikat is, hogy pl eloszor a dealer kap kartyat (Vagy nem) es ha kapott, akkor csekkoljuk blackjack-re meg bustedra is. ha ezek nem return-olnek, akkor kapunk mi kartyat, es magunkat is teszteljuk erre. Szoval picit atlathatobb lenne szerintem a kod. 
 - [x] Alapvetoen ezt a main-t kiszednem innet, es az `options`-os dolgokkal tennem egy helyre. Ezek azok a fuggvenyek, amik a user interaction-t kezelik. lehetne pl egy `blackjack_ui.py`. De ez csak javaslat. LEhetne persze jobban is cizellalni. Most ezt persze kicsit l'art pour l'art, de piciben jo rahangolodni erre :-)  

`justthecodes.py` <-- ennek nem latom, mi ertelme. Redundansan ne legyen meg a kod x peldanyban, mert csak "elmasznak" egymas mellol, ha valtoztatsz valamin. Szinkronban tartani oket szenvedos, ne kinozd vele magad.

`blackjack.py` <-- egyreszt ugyanaz, mint a fenti, viszont itt vannak tesztek, meg dokumentacio! (mondjuk a fenti sum dolog pont nincs letesztelve ;-)) Szuper, de ettol meg ne legyen kulon fajl. En most igy azt javasolnam, hogy a tobbit torold a fenebe, ezt modositsd / dobald szet ugy, ahogy fent javasoltam, valoszinuleg az a legegyszerubb. 

**Bottom line**: szep munka, a fentiek legyenek meg, a negyes tutira meglesz, az otoson gondolkodom, lehet ahhoz meg egy olyan dolgot kerni fogok, hogy a kimentett versenyeredmenyekbol tudjon valami statisztikat mutatni, hogy x alkalommal nyertem, ebbol y-szor blackjack-el, meg z-szer busted-elodtem (deszepenmegfogalmaztam). De elobb a fentiek.

**Comment by ujvarivera** [comment]
Szia. Elvileg minden javítás kész. Van log fájl is, meg statisztikát is lehet nézni a stat.py-ban.

"A `get***Card` most ha jol ertem, nem veszi ki a paklibol azt, amit a jatekosnak, dealernek letettunk. Ez szandekos?" kérdésre a válaszom: Igen szándékos. Ugye a Blackjacket eredetileg 52 lapos francia kártyával játsszák (13 érték, 4 szín), tehát minden értékű lap négyszer fordul elő. Na ezt nem igen tudtam volna kivitelezni, ezért egyszerűbbnek tartottam ha beállítok egy alap listát, amiben minden érték benne van, és a random segítségével mindig véletlenszerűen "kihúzunk" egyet. Igen, így egy lapot bárhányszor kihúzhatunk, de ez tűnt a legkönnyebb, ill. leglogikusabb megoldásnak.

**Comment by hegyhati** [comment]
Lesem. 

`sumOfTheCards`-nal nezz meg egy `[10,'A','A']` tesztet :-) 

Jatszottam x kort, es nem ertettem, hogy miert nem valtozik meg sosem a statisztika. Aztan megneztem a kodot: `open(r'SOE-ProgAlap1-Beadando-Blackjack-Ujvari\blackjack.log', 'a+')` Nekem nincs ilyen fajlom, igy sosem nyitja meg :-) miert nem csak siman `blackjack.log`?  Illetve amit nem ertek, hogy miert kinzod magad ezzel igy? Ez a log egy json, ha json-kent megnyitnad, es utana mint listahoz appendelnel, majd json-kent kiiratnad, akkor nem kellene vesszokkel szenvedni, meg stringkent kezelni, meg ilyenek. Ez igy ertheto?

Ezen kivul a problemam meg egyelore az, hogy tovabbra is megvan `blackjack.py` ahol duplikalva ott vannak a fajlok. Ezt nem tudtad letorolni, vagy elmaradt? 

Amugy szuper,az otost mar elkonyvelheted, de azert a fentieket meg jo volna kipofozni :-)

**Comment by ujvarivera** [comment]
Elvileg kész minden javitas.

**Comment by hegyhati** [comment]
Hehe, azert ez elegge behegesztett megoldas :-) 
![image](https://user-images.githubusercontent.com/13832329/103489363-5ce8b880-4e14-11eb-92b0-d3b79d89421d.png)

Tehat mi tortenik mondjuk a `[9,'A','A','A']` bemenetre? :-) Az egyszerubb irany az volna szerintem, hogyha mindegyik aszt 1-nek szamolnad, es a legvegen meg megnezned, hogy hanyszor 10-nek van meg hely (ez ugye max 2), es hany aszod volt. Es akkor a ketto kozul a kissebbik-szer 10-et meg hozzadsz. 

Node szep munka, vedd fel majd a vizsgat, mas dolgod nincs, mar csak en beirom az otost. 

Egy kerdes: annak abszolut orulok, hogy modnjuk hasznalod a `with`-et pedig nem tanitottam (bar nem vagyok benne teljesen biztos, hogy teljesen erted, mire jo), de azt jol sejtem, hogy abszolut nem az en leirasom alapjan csinalod a fajlkezelest? Marmint en abszolut nem mutattam olyat, hogy elobb olvassuk be egy stringbe a dolgot, aztan utana parzoljunk json-t.

**Comment by ujvarivera** [comment]
Javítottam a sum -ot. 
Azért használtam a with open-t ott, mert akkor külön nem kell a fáljbezárással foglalkozni.
A json-ös fájlkezeléssel még gondjaim vannak, ezért nézegettem utána kicsit a neten. Az előző parsolásos megoldást meg nem is értettem úgy igazán.

**Comment by hegyhati** [comment]
Hehe, jotanacs / okolszabaly, hogy a stackoverflow copy-paste egy hasznos dolog, de csak ugy erdemes csinalni, hogyha az ember, erti mit masol, es csak "idot sporol", kulonben gyakran visszanyal a fagyi.
